version: '3.7'
services:
  dev_container:
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace
    build:
      # context: where should docker-compose look for the Dockerfile?
      # i.e. either a path to a directory containing a Dockerfile, or a url to a git repository
      context: ..
      dockerfile: Dockerfile.dev
    env_file: 
      - ../.env
      #environment:
      #FLASK_CONFIG: development
      #FLASK_ENV: development
    # Forwards port 0.0.0.0:5003 from the Docker host (e.g. your computer) 
    # to the dev environment container's port 5000
    ports:
      - 0.0.0.0:8050:8050
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - tsd_network

  timescale:
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    env_file: 
      - ../.env
    volumes:
      - type: volume
        source: tsd_volume # the volume name
        target: /var/lib/postgresql/data # the location in the container where the data is stored
        read_only: false
    ports:
      - 0.0.0.0:5432:5432
    networks:
      - tsd_network

  pgadmin:
    image: "dpage/pgadmin4:latest"
    restart: unless-stopped
    env_file: 
      - ../.env
    environment:
      PGADMIN_LISTEN_PORT: 9000
    ports:
      - 0.0.0.0:9000:9000
    volumes:
      # So the database server settings get saved and stored even if the container is replaced or deleted
      - tsd_pgadmin_volume:/var/lib/pgadmin
    networks:
      - tsd_network

networks:
  tsd_network:
  # external: true

# Creates a named volume to persist our database data
volumes:
  tsd_volume:
  tsd_pgadmin_volume:

